# Generated by Django 4.2.6 on 2024-08-22 08:54

import apps.table.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0003_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.FileField(blank=True, upload_to=apps.table.models._get_avatar_filename),
        ),
    ]
